name: plant
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  fluttertoast: ^8.2.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  firebase_storage: ^12.3.6
  cloud_firestore: ^5.5.0

  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.4.0
  timezone: ^0.9.4

  provider: ^6.1.2
  shared_preferences: ^2.5.2
  http: ^1.2.2
  go_router: ^14.6.0
  firebase_messaging: ^15.1.6

  google_maps_flutter: ^2.12.1
  geolocator: ^13.0.4
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/basic_profile.png
